orientation:
  enabled: true
  raster_size: 512
  use_phase_correlation: true
  min_accept_score: 0.05
  sample_topk_rel: 0.2
  hist_bin_px: 4.0
  axis_snap_tol_deg: 2.0
coarse:
  enabled: true
  topk_rel_by_length: 0.1
  hv_angle_tol_deg: 6.0
  bins: 4096
  blur_sigma_bins: 1.5
  orientations: [0, 90, 180, 270]
  flips: [none, x, y]
  scale_quantiles: [0.05, 0.95]
  fallback_use_heatmap: true
  heatmap:
    raster: 1024
    blur_sigma_px: 2.0
    iters_phase: 1
  kdtree_match:
    angle_tol_deg: 4.0
    len_tol_rel: 0.15
    dist_tol_px: 8.0
    max_pairs: 3000
  score_weights:
    corr_x: 0.4
    corr_y: 0.4
    inliers: 0.2
  adapt:
    min_long_segments: 300
    relax_topk_rel: [0.1, 0.2, 0.4]
    relax_hv_angle: [6.0, 8.0, 10.0]
  refine_windows:
    scale_rel: 0.02
    shift_px: 8.0
    angle_deg: 3.0
  debug: false
rot_degrees: [0, 180]
angle_tol_deg: 6.0
curve_tol_rel: 0.001
straight_max_dev_rel: 0.0015
straight_max_angle_spread_deg: 3.0
min_seg_length_rel: 0.1
min_len_raw: 6.0
prefilter:
  len_rel_ref: diagonal
merge:
  enable: true
  collinear_angle_tol_deg: 3.0
  gap_max_rel: 0.003
  offset_tol_rel: 0.002
  thresholds:
    collinear_angle_tol_deg: 3.0
    gap_max_rel: 0.003
    offset_tol_rel: 0.002
grid:
  initial_cell_rel: 0.05
  final_cell_rel: 0.02
chamfer:
  sigma_rel: 0.004
  hard_mul: 3.0
refine:
  max_iters: 60
  max_samples: 1500
  scale_max_dev_rel: 0.02
  trans_max_dev_px: 8
ransac:
  iters: 60
  refine_scale_step: 0.004
  refine_trans_px: 3.0
  patience: 60
sampling:
  step_rel: 0.03
  max_points: 1500
verify:
  pick_k: 5
  diversity_rel: 0.10
  radius_px: 80
  dir_tol_deg: 6.0
  tol_rel: 0.01
  angle_tol_deg: 4.0
neighbors:
  use: true
  fast_signature: true
  radius_rel: 0.06
  dt: 0.03
  dtheta_deg: 8.0
cost_weights:
  endpoint: 0.5
  midpoint: 0.3
  direction: 0.2
  neighbors: 0.1
